### PR TITLE
test: rename integrity check index.test.ts, remove hello.yml

### PR DESCRIPTION
**Pull request by gabrielcalubayan72**

### CODE REVIEW

**Review by allainerain — COMMENTED** [review]
Maybe would be nice to delete stuff instead of commenting it out?

**Review by bbcarrots — CHANGES_REQUESTED** [review]
Tests looks fine! One last request: can you Right Click and then choose Format Document for a formatted document?

**Review by bbcarrots — CHANGES_REQUESTED** [review]
- Can you please add an `if (selectedOutputSN.studentRaws !== null)` condition for every test case that uses the `studentRaws` so it doesn't get a warning? 
- Please use an unique integer RFID for each dummy record.

I found a bug where it includes the 203100000 SN when selecting the student number from 2030 to 2030. Thanks, Gab!

**Comment by gabrielcalubayan72** [comment]
> * Can you please add an `if (selectedOutputSN.studentRaws !== null)` condition for every test case that uses the `studentRaws` so it doesn't get a warning?
> * Please use an unique integer RFID for each dummy record.
> 
> I found a bug where it includes the 203100000 SN when selecting the student number from 2030 to 2030. Thanks, Gab!

okay wait lang

**Review by bbcarrots — APPROVED** [review]
Almost all the backend functions are tested thoroughly! Thank you for the checks, Gab!

**Pull request merged**
