### PR TITLE
fix(Input.svelte): update regex for pattern validation

### PR DESCRIPTION
**Pull request by allainerain**
Regex Patterns for now:
1. First Name: alphabet, space, dash, apostrophes and ñ
2. Middle Initial: 1-2 capital letters
3. Last Name: alphabet, space, dash, apostrophes and ñ
4. Email: alphabet and numbers
5. Student Number: 9 digit number
6. Phone Number: 11 digit number

Added Titles for guided and more transparent warnings.

### CODE REVIEW

**Comment by allainerain** [comment]
Hi @gabrielcalubayan72! Please check if the current characters supported for the input validation is enough :D

**Comment by gabrielcalubayan72** [comment]
I also spotted an error in deleting student records via `localhostsmthsmth/dashboard/students`. After I confirm the deletion of one record, it also asks to confirm the deletion of the record below it. Is this expected behavior?

Please refer to the clip i will send via Discord for more details.

**Comment by allainerain** [comment]
Hi @gabrielcalubayan72, thanks for catching the bug! 🙇‍♀️🙇‍♀️ I got to fix the bug for the deletion and I added the apostrophes already for the pattern validation for the first name and last name input. Let me know if I missed anything else 😄

**Comment by gabrielcalubayan72** [comment]
oks wait will check later

**Review by gabrielcalubayan72 — APPROVED** [review]
wow five star review stellar dialogue and screenplay

**Pull request merged**
